import type { ProducerSuggestion } from './producerModeTypes.js';

export const PRODUCER_MODE_EMPTY_PROJECT: ProducerSuggestion = {
  id: 'start-with-loop',
  category: 'rhythm',
  priority: 'high',
  title: 'Start With a Core Loop',
  body: 'Start with a drum loop or MIDI pattern.',
  actionLabel: 'Show Arrangement',
  guideTarget: 'arrangement',
};

export const PRODUCER_MODE_SUGGESTIONS = {
  shortArrangement: {
    id: 'build-loop',
    category: 'arrangement',
    priority: 'high',
    title: 'Build the Loop First',
    body: 'Build an 8–16 bar loop before arranging a full song.',
    actionLabel: 'Focus Arrangement',
    guideTarget: 'arrangement',
  },
  midiOnly: {
    id: 'layer-audio',
    category: 'rhythm',
    priority: 'medium',
    title: 'Layer Audio Texture',
    body: 'Try layering audio drums or texture under your MIDI.',
    actionLabel: 'Open Browser',
    guideTarget: 'browser',
  },
  audioOnly: {
    id: 'add-midi',
    category: 'bass',
    priority: 'medium',
    title: 'Add a MIDI Part',
    body: 'Try adding a MIDI bassline or lead.',
    actionLabel: 'Open Piano Roll',
    guideTarget: 'piano-roll',
  },
  downtempo: {
    id: 'tempo-downtempo',
    category: 'workflow',
    priority: 'low',
    title: 'Tempo Character',
    body: 'This tempo is good for downtempo, trap, hip-hop, or ambient.',
    guideTarget: 'transport',
  },
  dance: {
    id: 'tempo-dance',
    category: 'workflow',
    priority: 'low',
    title: 'Tempo Character',
    body: 'This tempo works well for house, techno, pop, and dance.',
    guideTarget: 'transport',
  },
  bassMusic: {
    id: 'tempo-bass',
    category: 'workflow',
    priority: 'low',
    title: 'Tempo Character',
    body: 'This tempo is strong for dubstep, riddim, trap, and hybrid bass.',
    guideTarget: 'transport',
  },
  muteSolo: {
    id: 'use-mute-solo',
    category: 'mix',
    priority: 'medium',
    title: 'Use Mute/Solo',
    body: 'Use mute/solo to compare sections and isolate mix problems.',
    actionLabel: 'Open Mixer',
    guideTarget: 'mixer',
  },
  save: {
    id: 'save-before-experimenting',
    category: 'workflow',
    priority: 'high',
    title: 'Save Before Experiments',
    body: 'Save your project before experimenting further.',
    actionLabel: 'Highlight Save',
    guideTarget: 'save',
  },
  export: {
    id: 'export-test-bounce',
    category: 'export',
    priority: 'medium',
    title: 'Make a Test Bounce',
    body: 'When your loop feels solid, export a WAV test bounce.',
    actionLabel: 'Highlight Export',
    guideTarget: 'export',
  },
} satisfies Record<string, ProducerSuggestion>;
